[package]
name = "compiler_ii"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.24"
xml_writer = "0.4"
tempfile = "2.1"
